//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLighthouseWavesPlayerVideoApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLighthouseWavesPlayerVideoApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite videos yet..
        /// </summary>
        internal static string Favorites_NoVideos {
            get {
                return ResourceManager.GetString("Favorites_NoVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Favorites.
        /// </summary>
        internal static string Favorites_Refresh {
            get {
                return ResourceManager.GetString("Favorites_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Favorites_Remove {
            get {
                return ResourceManager.GetString("Favorites_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search favorites....
        /// </summary>
        internal static string Favorites_Search {
            get {
                return ResourceManager.GetString("Favorites_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites_Title {
            get {
                return ResourceManager.GetString("Favorites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fav.
        /// </summary>
        internal static string Library_AddFavorite {
            get {
                return ResourceManager.GetString("Library_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No videos found. Ensure storage permission is granted..
        /// </summary>
        internal static string Library_NoVideos {
            get {
                return ResourceManager.GetString("Library_NoVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Library.
        /// </summary>
        internal static string Library_Refresh {
            get {
                return ResourceManager.GetString("Library_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Library_RemoveFavorite {
            get {
                return ResourceManager.GetString("Library_RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search videos....
        /// </summary>
        internal static string Library_Search {
            get {
                return ResourceManager.GetString("Library_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Library.
        /// </summary>
        internal static string Library_Title {
            get {
                return ResourceManager.GetString("Library_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string Permissions_Open_Settings {
            get {
                return ResourceManager.GetString("Permissions_Open_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs access to your videos to display them. Please grant the permission in the app settings..
        /// </summary>
        internal static string Permissions_Storage_Message {
            get {
                return ResourceManager.GetString("Permissions_Storage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Required.
        /// </summary>
        internal static string Permissions_Storage_Title {
            get {
                return ResourceManager.GetString("Permissions_Storage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Player_AddFavorite {
            get {
                return ResourceManager.GetString("Player_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video playback error.
        /// </summary>
        internal static string Player_Error_Playback {
            get {
                return ResourceManager.GetString("Player_Error_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Player_Error_Title {
            get {
                return ResourceManager.GetString("Player_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permission is required to save screenshots to the gallery. Please grant permission in app settings..
        /// </summary>
        internal static string Player_Permission_Error {
            get {
                return ResourceManager.GetString("Player_Permission_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite.
        /// </summary>
        internal static string Player_RemoveFavorite {
            get {
                return ResourceManager.GetString("Player_RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume from {0}?.
        /// </summary>
        internal static string Player_ResumeDialog_Message {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Player_ResumeDialog_Resume {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        internal static string Player_ResumeDialog_StartOver {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Playback?.
        /// </summary>
        internal static string Player_ResumeDialog_Title {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Screenshot.
        /// </summary>
        internal static string Player_Screenshot {
            get {
                return ResourceManager.GetString("Player_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to take screenshot..
        /// </summary>
        internal static string Player_Screenshot_Error {
            get {
                return ResourceManager.GetString("Player_Screenshot_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot saved to gallery.
        /// </summary>
        internal static string Player_Screenshot_Success {
            get {
                return ResourceManager.GetString("Player_Screenshot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player_Title {
            get {
                return ResourceManager.GetString("Player_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Mute.
        /// </summary>
        internal static string Player_ToggleMute {
            get {
                return ResourceManager.GetString("Player_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Subtitles.
        /// </summary>
        internal static string Player_ToggleSubtitles {
            get {
                return ResourceManager.GetString("Player_ToggleSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Information.
        /// </summary>
        internal static string Player_VideoInfo {
            get {
                return ResourceManager.GetString("Player_VideoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Playlist.
        /// </summary>
        internal static string Playlists_AddNew {
            get {
                return ResourceManager.GetString("Playlists_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        internal static string Playlists_AddToPlaylist {
            get {
                return ResourceManager.GetString("Playlists_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Playlists_Cancel {
            get {
                return ResourceManager.GetString("Playlists_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the playlist &apos;{0}&apos;?.
        /// </summary>
        internal static string Playlists_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("Playlists_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Playlists_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Playlists_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Playlist.
        /// </summary>
        internal static string Playlists_Create {
            get {
                return ResourceManager.GetString("Playlists_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Playlists_CreateButton {
            get {
                return ResourceManager.GetString("Playlists_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap + to create your first playlist.
        /// </summary>
        internal static string Playlists_CreateFirst {
            get {
                return ResourceManager.GetString("Playlists_CreateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any playlists yet. Create a playlist first..
        /// </summary>
        internal static string Playlists_CreateFirstMessage {
            get {
                return ResourceManager.GetString("Playlists_CreateFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        internal static string Playlists_Description {
            get {
                return ResourceManager.GetString("Playlists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlists yet.
        /// </summary>
        internal static string Playlists_EmptyList {
            get {
                return ResourceManager.GetString("Playlists_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name cannot be empty..
        /// </summary>
        internal static string Playlists_EmptyName {
            get {
                return ResourceManager.GetString("Playlists_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Playlist.
        /// </summary>
        internal static string Playlists_EmptyPlaylist {
            get {
                return ResourceManager.GetString("Playlists_EmptyPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Playlists_Error {
            get {
                return ResourceManager.GetString("Playlists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create playlist..
        /// </summary>
        internal static string Playlists_ErrorCreating {
            get {
                return ResourceManager.GetString("Playlists_ErrorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete playlist..
        /// </summary>
        internal static string Playlists_ErrorDeleting {
            get {
                return ResourceManager.GetString("Playlists_ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load playlists..
        /// </summary>
        internal static string Playlists_ErrorLoading {
            get {
                return ResourceManager.GetString("Playlists_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update playlists: {0}.
        /// </summary>
        internal static string Playlists_ErrorMessage {
            get {
                return ResourceManager.GetString("Playlists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to play playlist..
        /// </summary>
        internal static string Playlists_ErrorPlaying {
            get {
                return ResourceManager.GetString("Playlists_ErrorPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Name.
        /// </summary>
        internal static string Playlists_Name {
            get {
                return ResourceManager.GetString("Playlists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Playlists_No {
            get {
                return ResourceManager.GetString("Playlists_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Playlists.
        /// </summary>
        internal static string Playlists_NoPlaylists {
            get {
                return ResourceManager.GetString("Playlists_NoPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This playlist has no videos to play.
        /// </summary>
        internal static string Playlists_NoVideosToPlay {
            get {
                return ResourceManager.GetString("Playlists_NoVideosToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Playlists_Save {
            get {
                return ResourceManager.GetString("Playlists_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Playlists_Success {
            get {
                return ResourceManager.GetString("Playlists_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string Playlists_Title {
            get {
                return ResourceManager.GetString("Playlists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists updated successfully.
        /// </summary>
        internal static string Playlists_UpdateSuccess {
            get {
                return ResourceManager.GetString("Playlists_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Playlists_Yes {
            get {
                return ResourceManager.GetString("Playlists_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Search_Clear {
            get {
                return ResourceManager.GetString("Search_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will use the selected language..
        /// </summary>
        internal static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string Settings_LanguagePickerTitle {
            get {
                return ResourceManager.GetString("Settings_LanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string Settings_ResetButton {
            get {
                return ResourceManager.GetString("Settings_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will use the selected theme..
        /// </summary>
        internal static string Settings_ThemeHint {
            get {
                return ResourceManager.GetString("Settings_ThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Settings_ThemeLabel {
            get {
                return ResourceManager.GetString("Settings_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        internal static string Settings_ThemePickerTitle {
            get {
                return ResourceManager.GetString("Settings_ThemePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System (Auto).
        /// </summary>
        internal static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Shell_Favorites {
            get {
                return ResourceManager.GetString("Shell_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Shell_Library {
            get {
                return ResourceManager.GetString("Shell_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string Shell_Playlists {
            get {
                return ResourceManager.GetString("Shell_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Shell_Settings {
            get {
                return ResourceManager.GetString("Shell_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player.
        /// </summary>
        internal static string Shell_Title {
            get {
                return ResourceManager.GetString("Shell_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string Sort_By {
            get {
                return ResourceManager.GetString("Sort_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (Short-Long).
        /// </summary>
        internal static string Sort_DurationAsc {
            get {
                return ResourceManager.GetString("Sort_DurationAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (Long-Short).
        /// </summary>
        internal static string Sort_DurationDesc {
            get {
                return ResourceManager.GetString("Sort_DurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (A-Z).
        /// </summary>
        internal static string Sort_TitleAsc {
            get {
                return ResourceManager.GetString("Sort_TitleAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (Z-A).
        /// </summary>
        internal static string Sort_TitleDesc {
            get {
                return ResourceManager.GetString("Sort_TitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Information.
        /// </summary>
        internal static string VideoInfo_Header {
            get {
                return ResourceManager.GetString("VideoInfo_Header", resourceCulture);
            }
        }
    }
}
