//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLighthouseWavesPlayerVideoApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheLighthouseWavesPlayerVideoApp.Resources.Languages.AppResources.ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранных видео пока нет..
        /// </summary>
        internal static string Favorites_NoVideos {
            get {
                return ResourceManager.GetString("Favorites_NoVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить избранное.
        /// </summary>
        internal static string Favorites_Refresh {
            get {
                return ResourceManager.GetString("Favorites_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Favorites_Remove {
            get {
                return ResourceManager.GetString("Favorites_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск в избранном....
        /// </summary>
        internal static string Favorites_Search {
            get {
                return ResourceManager.GetString("Favorites_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранное.
        /// </summary>
        internal static string Favorites_Title {
            get {
                return ResourceManager.GetString("Favorites_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избр.
        /// </summary>
        internal static string Library_AddFavorite {
            get {
                return ResourceManager.GetString("Library_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео не найдены. Убедитесь, что предоставлены разрешения на хранилище..
        /// </summary>
        internal static string Library_NoVideos {
            get {
                return ResourceManager.GetString("Library_NoVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить библиотеку.
        /// </summary>
        internal static string Library_Refresh {
            get {
                return ResourceManager.GetString("Library_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Library_RemoveFavorite {
            get {
                return ResourceManager.GetString("Library_RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск видео....
        /// </summary>
        internal static string Library_Search {
            get {
                return ResourceManager.GetString("Library_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеотека.
        /// </summary>
        internal static string Library_Title {
            get {
                return ResourceManager.GetString("Library_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть настройки.
        /// </summary>
        internal static string Permissions_Open_Settings {
            get {
                return ResourceManager.GetString("Permissions_Open_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этому приложению нужен доступ к вашим видео для их отображения. Пожалуйста, предоставьте разрешение в настройках приложения..
        /// </summary>
        internal static string Permissions_Storage_Message {
            get {
                return ResourceManager.GetString("Permissions_Storage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется разрешение.
        /// </summary>
        internal static string Permissions_Storage_Title {
            get {
                return ResourceManager.GetString("Permissions_Storage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В избранное.
        /// </summary>
        internal static string Player_AddFavorite {
            get {
                return ResourceManager.GetString("Player_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка воспроизведения видео.
        /// </summary>
        internal static string Player_Error_Playback {
            get {
                return ResourceManager.GetString("Player_Error_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Player_Error_Title {
            get {
                return ResourceManager.GetString("Player_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сохранения снимков экрана в галерею требуется разрешение на доступ к хранилищу. Предоставьте разрешение в настройках приложения..
        /// </summary>
        internal static string Player_Permission_Error {
            get {
                return ResourceManager.GetString("Player_Permission_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из избранного.
        /// </summary>
        internal static string Player_RemoveFavorite {
            get {
                return ResourceManager.GetString("Player_RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить с {0}?.
        /// </summary>
        internal static string Player_ResumeDialog_Message {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        internal static string Player_ResumeDialog_Resume {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать сначала.
        /// </summary>
        internal static string Player_ResumeDialog_StartOver {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить воспроизведение?.
        /// </summary>
        internal static string Player_ResumeDialog_Title {
            get {
                return ResourceManager.GetString("Player_ResumeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать снимок экрана.
        /// </summary>
        internal static string Player_Screenshot {
            get {
                return ResourceManager.GetString("Player_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сделать снимок экрана..
        /// </summary>
        internal static string Player_Screenshot_Error {
            get {
                return ResourceManager.GetString("Player_Screenshot_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снимок экрана сохранен в галерею.
        /// </summary>
        internal static string Player_Screenshot_Success {
            get {
                return ResourceManager.GetString("Player_Screenshot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плеер.
        /// </summary>
        internal static string Player_Title {
            get {
                return ResourceManager.GetString("Player_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкл/Выкл звук.
        /// </summary>
        internal static string Player_ToggleMute {
            get {
                return ResourceManager.GetString("Player_ToggleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкл/Выкл субтитры.
        /// </summary>
        internal static string Player_ToggleSubtitles {
            get {
                return ResourceManager.GetString("Player_ToggleSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о видео.
        /// </summary>
        internal static string Player_VideoInfo {
            get {
                return ResourceManager.GetString("Player_VideoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый плейлист.
        /// </summary>
        internal static string Playlists_AddNew {
            get {
                return ResourceManager.GetString("Playlists_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в плейлист.
        /// </summary>
        internal static string Playlists_AddToPlaylist {
            get {
                return ResourceManager.GetString("Playlists_AddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Playlists_Cancel {
            get {
                return ResourceManager.GetString("Playlists_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить плейлист &apos;{0}&apos;?.
        /// </summary>
        internal static string Playlists_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("Playlists_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        internal static string Playlists_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Playlists_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый плейлист.
        /// </summary>
        internal static string Playlists_Create {
            get {
                return ResourceManager.GetString("Playlists_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Playlists_CreateButton {
            get {
                return ResourceManager.GetString("Playlists_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите + чтобы создать ваш первый плейлист.
        /// </summary>
        internal static string Playlists_CreateFirst {
            get {
                return ResourceManager.GetString("Playlists_CreateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас пока нет плейлистов. Сначала создайте плейлист..
        /// </summary>
        internal static string Playlists_CreateFirstMessage {
            get {
                return ResourceManager.GetString("Playlists_CreateFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (необязательно).
        /// </summary>
        internal static string Playlists_Description {
            get {
                return ResourceManager.GetString("Playlists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлистов пока нет.
        /// </summary>
        internal static string Playlists_EmptyList {
            get {
                return ResourceManager.GetString("Playlists_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название плейлиста не может быть пустым..
        /// </summary>
        internal static string Playlists_EmptyName {
            get {
                return ResourceManager.GetString("Playlists_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой плейлист.
        /// </summary>
        internal static string Playlists_EmptyPlaylist {
            get {
                return ResourceManager.GetString("Playlists_EmptyPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Playlists_Error {
            get {
                return ResourceManager.GetString("Playlists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось создать плейлист..
        /// </summary>
        internal static string Playlists_ErrorCreating {
            get {
                return ResourceManager.GetString("Playlists_ErrorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось удалить плейлист..
        /// </summary>
        internal static string Playlists_ErrorDeleting {
            get {
                return ResourceManager.GetString("Playlists_ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить плейлисты..
        /// </summary>
        internal static string Playlists_ErrorLoading {
            get {
                return ResourceManager.GetString("Playlists_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обновить плейлисты: {0}.
        /// </summary>
        internal static string Playlists_ErrorMessage {
            get {
                return ResourceManager.GetString("Playlists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось воспроизвести плейлист..
        /// </summary>
        internal static string Playlists_ErrorPlaying {
            get {
                return ResourceManager.GetString("Playlists_ErrorPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название плейлиста.
        /// </summary>
        internal static string Playlists_Name {
            get {
                return ResourceManager.GetString("Playlists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string Playlists_No {
            get {
                return ResourceManager.GetString("Playlists_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет плейлистов.
        /// </summary>
        internal static string Playlists_NoPlaylists {
            get {
                return ResourceManager.GetString("Playlists_NoPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этом плейлисте нет видео для воспроизведения.
        /// </summary>
        internal static string Playlists_NoVideosToPlay {
            get {
                return ResourceManager.GetString("Playlists_NoVideosToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Playlists_Save {
            get {
                return ResourceManager.GetString("Playlists_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно.
        /// </summary>
        internal static string Playlists_Success {
            get {
                return ResourceManager.GetString("Playlists_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлисты.
        /// </summary>
        internal static string Playlists_Title {
            get {
                return ResourceManager.GetString("Playlists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлисты успешно обновлены.
        /// </summary>
        internal static string Playlists_UpdateSuccess {
            get {
                return ResourceManager.GetString("Playlists_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Playlists_Yes {
            get {
                return ResourceManager.GetString("Playlists_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        internal static string Search_Clear {
            get {
                return ResourceManager.GetString("Search_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки приложения.
        /// </summary>
        internal static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение будет использовать выбранный язык..
        /// </summary>
        internal static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        internal static string Settings_LanguagePickerTitle {
            get {
                return ResourceManager.GetString("Settings_LanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить настройки.
        /// </summary>
        internal static string Settings_ResetButton {
            get {
                return ResourceManager.GetString("Settings_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темная.
        /// </summary>
        internal static string Settings_ThemeDark {
            get {
                return ResourceManager.GetString("Settings_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение будет использовать выбранную тему..
        /// </summary>
        internal static string Settings_ThemeHint {
            get {
                return ResourceManager.GetString("Settings_ThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        internal static string Settings_ThemeLabel {
            get {
                return ResourceManager.GetString("Settings_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        internal static string Settings_ThemeLight {
            get {
                return ResourceManager.GetString("Settings_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тему.
        /// </summary>
        internal static string Settings_ThemePickerTitle {
            get {
                return ResourceManager.GetString("Settings_ThemePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системная (Авто).
        /// </summary>
        internal static string Settings_ThemeSystem {
            get {
                return ResourceManager.GetString("Settings_ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранное.
        /// </summary>
        internal static string Shell_Favorites {
            get {
                return ResourceManager.GetString("Shell_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотека.
        /// </summary>
        internal static string Shell_Library {
            get {
                return ResourceManager.GetString("Shell_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлисты.
        /// </summary>
        internal static string Shell_Playlists {
            get {
                return ResourceManager.GetString("Shell_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Shell_Settings {
            get {
                return ResourceManager.GetString("Shell_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео плеер.
        /// </summary>
        internal static string Shell_Title {
            get {
                return ResourceManager.GetString("Shell_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по:.
        /// </summary>
        internal static string Sort_By {
            get {
                return ResourceManager.GetString("Sort_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность (Короткие-Длинные).
        /// </summary>
        internal static string Sort_DurationAsc {
            get {
                return ResourceManager.GetString("Sort_DurationAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность (Длинные-Короткие).
        /// </summary>
        internal static string Sort_DurationDesc {
            get {
                return ResourceManager.GetString("Sort_DurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (А-Я).
        /// </summary>
        internal static string Sort_TitleAsc {
            get {
                return ResourceManager.GetString("Sort_TitleAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (Я-А).
        /// </summary>
        internal static string Sort_TitleDesc {
            get {
                return ResourceManager.GetString("Sort_TitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о видео.
        /// </summary>
        internal static string VideoInfo_Header {
            get {
                return ResourceManager.GetString("VideoInfo_Header", resourceCulture);
            }
        }
    }
}
